version: '3'
services:
  rails:
    build: .
    command: rails s -b 0.0.0.0
    container_name: freelancertd7
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
    expose:
      - "3000"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
      - redis
    networks:
      - freelancer
      - db_network
      - redis_network
  
  redis:
    command: "redis-server"
    container_name: redis
    restart: always
    image: redis
    networks:
      - redis_network

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - freelancertd7_data:/var/lib/postgresql/data
    networks:
      - db_network

networks: 
  freelancer: 
    external: true
  db_network:
    external: false
  redis_network:
    external: false
    
volumes:
  freelancertd7_data:
  redis: